
enable_gripper_grasp=True
enable_suction_grasp=False

sample_action_with_argmax=False
enable_gripper_shift=False
enable_suction_shift=False
activate_refine_point_cloud=False
simulation_mode = False
offline_point_cloud= False
report_result=False
report_for_handover=False
report_for_shift=False
report_for_grasp=True
single_arm_operation_mode=False
activate_segmentation_queries=False
activate_preferred_placement_side=False
activate_handover=True
only_handover=True
activate_shift_from_beneath_objects=True

use_analytical_normal_estimation=True

quality_exponent=2.0
handover_quality_bias=10.
gripper_grasp_bias=0.
suction_grasp_bias=0.

enhance_gripper_firmness=True
zero_out_distance_when_collision=False

view_sampled_griper=False
view_sampled_suction=False

highest_elevation_to_grasp=0.2

suction_limit=0.5
gripper_limit=0.5
suction_factor=1.0
gripper_factor=1.0

bin_collision_threshold=0.7
objects_collision_threshold=0.5

suction_reachablity_threshold=0.4
gripper_reachablity_threshold=0.4

activate_gripper_quality_mask=False
activate_suction_quality_mask=False

activate_grasp_quality_check=True
