
enable_gripper_grasp=True
enable_suction_grasp=True

sample_action_with_argmax=False
enable_gripper_shift=True
enable_suction_shift=True
activate_refine_point_cloud=False
simulation_mode = False
offline_point_cloud= False
report_result=True
report_for_handover=False
report_for_shift=False
report_for_grasp=True
single_arm_operation_mode=False
activate_segmentation_queries=False
activate_preferred_placement_side=False
activate_handover=False
only_handover=False
activate_shift_from_beneath_objects=True

use_analytical_normal_estimation=True

quality_exponent=1.0
handover_quality_bias=10.
gripper_grasp_bias=0.
suction_grasp_bias=0.

enhance_gripper_firmness=True
zero_out_distance_when_collision=False

minimum_penetration_distance_ratio=0.05

view_sampled_griper=False
view_sampled_suction=False

highest_elevation_to_grasp=0.2

suction_factor=1.0
gripper_factor=1.0

bin_collision_threshold=0.5
objects_collision_threshold=0.5

suction_reachablity_threshold=0.5
gripper_reachablity_threshold=0.5

activate_gripper_quality_mask=True
activate_suction_quality_mask=True

activate_grasp_quality_check=True
